# Generated by Django 5.0.3 on 2024-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_productmaterial_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmaterial",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
