# Generated by Django 5.0.3 on 2024-03-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productmaterial_quantity"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="material",
            table="materials",
        ),
        migrations.AlterModelTable(
            name="product",
            table="products",
        ),
        migrations.AlterModelTable(
            name="productmaterial",
            table="product_materials",
        ),
        migrations.AlterModelTable(
            name="warehouse",
            table="warehouses",
        ),
    ]
